"""Add expected_salary

Revision ID: f87b18249b1c
Revises: 545581e3f15c
Create Date: 2026-09-27 12:33:18.286198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87b18249b1c'
down_revision: Union[str, Sequence[str], None] = '545581e3f15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('expected_salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'expected_salary')
    # ### end Alembic commands ###
